concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.number }}
jobs:
  main:
    name: Check pull request title
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: amannn/action-semantic-pull-request@v5.5.2
      with:
        headerPattern: ^\[(\w*?)\](?:\[(.*?)\])?(?:\s*)(.*)$
        headerPatternCorrespondence: type, scope, subject
        scopes: 'admin

          bk

          broker

          build

          ci

          cli

          client

          doc

          fn

          io

          meta

          misc

          ml

          monitor

          offload

          proxy

          schema

          sec

          site

          storage

          test

          txn

          ws

          zk

          pip

          '
        types: 'cleanup

          feat

          fix

          improve

          refactor

          revert

          '
name: Semantic Pull Request
on:
  repository_dispatch:
    types: trigger-ga___ci-semantic-pull-request.yml
